### PR TITLE
Fill template and save from file upload field

### PR DESCRIPTION
**Pull request by lsgs**
File upload field dialog enables selection of template to fill and save to field as an alternative to selecting an existing file.
Module project settings for alternative paper size and orientation for templates.

### CODE REVIEW

**Comment by remifrazierucsf** [comment]
@BCCHR-IT @lsgs let us know if there's anything we can do to support this PR at this time.

**Comment by 274188A** [comment]
@remifrazierucsf  - I went ahead and tried out manually copying over @lsgs (Luke's) files form his PR - no problems so far.  I suggest it might be a good idea to do a [transfer of 'Ownership'](https://docs.github.com/en/developers/apps/managing-github-apps/transferring-ownership-of-a-github-app) for this repo given the current owners seem indisposed for long periods of time.

**Comment by remifrazierucsf** [comment]
@BCCHR-IT is there any chance that this feature request will be (or has been) merged in for the next release? We can provide some engineering support for this if that would help.

(Moved this comment over here from the closed #22 where I accidentally posted it originally.)

**Comment by BCCHR-IT** [comment]
@remifrazierucsf it wasn't pulled in to the PHP8 compatibility update, no. The original PR has some conflicts with the current changes that I haven't gone through yet, as I now have to focus on the changes needed to use RC's new data export rights scheme.

If you have the capacity to resolve the conflicts between that original PR and the current main, I can test them and merge if they're successful.

**Comment by remifrazierucsf** [comment]
@BCCHR-IT we will take a look. Thanks!

**Comment by remifrazierucsf** [comment]
@BCCHR-IT are you okay with us still looking at this? We're almost ready to finally.

**Comment by BCCHR-IT** [comment]
> @BCCHR-IT are you okay with us still looking at this? We're almost ready to finally.

Hi @remifrazierucsf , I have just pushed the v4.0.0 update to the consortium for review and hopeful release. If you have the bandwidth to look at the proposed changes vs the new v4 codebase, that would be appreciated!

**Comment by remifrazierucsf** [comment]
@lsgs was this item actually implemented in 4.0.0?

**Comment by lsgs** [comment]
No @remifrazierucsf, it wasn't. The PR was pretty messy though. I have just done a couple of new ones based on v4.0.0, one for each of the two additional features:
1. Project settings for template paper size and orientation ([pull/55](https://github.com/BCCHR-IT/custom-template-engine/pull/55))
2. Integration with data entry form file upload fields ([pull/56](https://github.com/BCCHR-IT/custom-template-engine/pull/56))

**Pull request closed without merging**
